# Generated by Django 3.1.5 on 2021-02-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('address', models.CharField(max_length=90, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'ORGANIZATION'), (3, 'EVALUATOR'), (4, 'CUSTOMER')], default=0)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('Second_name', models.CharField(max_length=30, verbose_name='second name')),
                ('Third_name', models.CharField(max_length=30, verbose_name='Third name')),
                ('Fourth_name', models.CharField(max_length=30, verbose_name='Fourth name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('Business_name', models.CharField(blank=True, max_length=90, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
